language: node_js
node_js:
  - "6"
  - "8"

sudo: false

before_install:
  - npm install
  - ( bin/sproutcore serve --local-only=true --port=4020 --include-tests --disable-bt-feedback & ) || /bin/true
  - sleep 15

script: node tests/core.js
